name: Update joke

# ToDo: Change to a scheduled trigger
# on:
#   schedule:
#     - cron: "*/5 * * * *"

on:
  issue_comment:

jobs:
  funny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - run: node new-joke.js
      - run: |
          git config --global user.name 'Jokebot'
          git config --global user.email 'funny.joke@pm.me'
          git commit -am "Funny joke"
          git push
