name: Update joke

on:
  schedule:
    - cron: '1 0 */1 * *'

# For debugging you can trigger the workflow with a comment
# on:
#   issue_comment:

jobs:
  funny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.HAPPY_BOT_TOKEN }}
      - uses: actions/setup-node@v1
      - run: node new-joke.js
      - run: |
          git config --global user.name 'HappyBot'
          git config --global user.email 'h-a-p-p-y-b-o-t@users.noreply.github.com'
          git commit -am "Updated joke"
          git push
